# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'podcast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for podcast
  pod 'URLNavigator'
  pod 'Kingfisher', '~> 5.0'
  pod "BonMot"
  pod "SnapKit"
  pod 'Moya'
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'IQKeyboardManager'
  pod 'Toast-Swift'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
